/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 34
#line 1 "kml.leg"

           #include <stdio.h>     /* printf() */
           #include <stdlib.h>    /* atoi() */
           #include <vector>
           #include "KML.h"
           #include "generator.hpp"
           #include <iostream>
           int vars[26];
           int i = 0;
           NodePtr program(0);

           #define DEBUG 0
           

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_COMMA_DELIMETER(yycontext *yy); /* 34 */
YY_RULE(int) yy_NUMBER_LITERAL(yycontext *yy); /* 33 */
YY_RULE(int) yy_CLOSE_COORDINATE(yycontext *yy); /* 32 */
YY_RULE(int) yy_SINGLECOR(yycontext *yy); /* 31 */
YY_RULE(int) yy_OPEN_COORDINATE(yycontext *yy); /* 30 */
YY_RULE(int) yy_CLOSE_POINT(yycontext *yy); /* 29 */
YY_RULE(int) yy_OPEN_POINT(yycontext *yy); /* 28 */
YY_RULE(int) yy_CLOSE_DESCRIPTION(yycontext *yy); /* 27 */
YY_RULE(int) yy_OPEN_DESCRIPTION(yycontext *yy); /* 26 */
YY_RULE(int) yy_CLOSE_NAME(yycontext *yy); /* 25 */
YY_RULE(int) yy_STRING_LITERAL(yycontext *yy); /* 24 */
YY_RULE(int) yy_OPEN_NAME(yycontext *yy); /* 23 */
YY_RULE(int) yy_FULL_POINT_TAG(yycontext *yy); /* 22 */
YY_RULE(int) yy_FULL_DESCRIPTION_TAG(yycontext *yy); /* 21 */
YY_RULE(int) yy_FULL_NAME_TAG(yycontext *yy); /* 20 */
YY_RULE(int) yy_MINOR_TAGS(yycontext *yy); /* 19 */
YY_RULE(int) yy_CLOSE_LINESTRING(yycontext *yy); /* 18 */
YY_RULE(int) yy_COORDINATES_LIST(yycontext *yy); /* 17 */
YY_RULE(int) yy_OPEN_LINESTRING(yycontext *yy); /* 16 */
YY_RULE(int) yy_CLOSE_PLACEMARKER(yycontext *yy); /* 15 */
YY_RULE(int) yy_DESCRIPTORS(yycontext *yy); /* 14 */
YY_RULE(int) yy_OPEN_PLACEMARKER(yycontext *yy); /* 13 */
YY_RULE(int) yy_FULL_LINESTRING_TAG(yycontext *yy); /* 12 */
YY_RULE(int) yy_FULL_PLACEMARKER_TAG(yycontext *yy); /* 11 */
YY_RULE(int) yy_CLOSE_DOCUMENT(yycontext *yy); /* 10 */
YY_RULE(int) yy_MAJOR_TAGS(yycontext *yy); /* 9 */
YY_RULE(int) yy_OPEN_DOCUMENT(yycontext *yy); /* 8 */
YY_RULE(int) yy_CLOSE_KML(yycontext *yy); /* 7 */
YY_RULE(int) yy_DOCUMENT(yycontext *yy); /* 6 */
YY_RULE(int) yy_OPEN_KML(yycontext *yy); /* 5 */
YY_RULE(int) yy_WS(yycontext *yy); /* 4 */
YY_RULE(int) yy_EOL(yycontext *yy); /* 3 */
YY_RULE(int) yy_KML_DOC(yycontext *yy); /* 2 */
YY_RULE(int) yy_PROGRAM(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_STRING_LITERAL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRING_LITERAL\n"));
  {
#line 119
  __ = NodePtr(new StringLiteralNode(yytext)); printf("STRING-LITERAL %s\n",yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NUMBER_LITERAL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NUMBER_LITERAL\n"));
  {
#line 118
  __ = NodePtr(new NumberLiteralNode(atoi(yytext))); printf("NUMBER-LITERAL %d\n",atoi(yytext));;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_EOL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EOL\n"));
  {
#line 117
  printf("EOL\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_WS(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_WS\n"));
  {
#line 116
  printf("WS\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_COMMA_DELIMETER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_COMMA_DELIMETER\n"));
  {
#line 115
  printf("COMMA-DELIMETER\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_COORDINATE(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_COORDINATE\n"));
  {
#line 113
  printf("CLOSE-COORDINATE\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_COORDINATE(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_COORDINATE\n"));
  {
#line 112
  printf("OPEN-COORDINATE\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_POINT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_POINT\n"));
  {
#line 111
  printf("CLOSE-POINT\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_POINT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_POINT\n"));
  {
#line 110
  printf("OPEN-POINT\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_DESCRIPTION(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_DESCRIPTION\n"));
  {
#line 109
  printf("CLOSE-DESCRIPTION\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_DESCRIPTION(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_DESCRIPTION\n"));
  {
#line 108
  printf("OPEN-DESCRIPTION\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_NAME(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_NAME\n"));
  {
#line 107
  printf("CLOSE-NAME\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_NAME(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_NAME\n"));
  {
#line 106
  printf("OPEN-NAME\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_PLACEMARKER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_PLACEMARKER\n"));
  {
#line 105
  printf("CLOSE-PLACEMARKER\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_PLACEMARKER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_PLACEMARKER\n"));
  {
#line 104
  printf("OPEN-PLACEMARKER\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_LINESTRING(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_LINESTRING\n"));
  {
#line 103
  printf("CLOSE-LINESTRING\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_LINESTRING(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_LINESTRING\n"));
  {
#line 102
  printf("OPEN-LINESTRING\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_DOCUMENT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_DOCUMENT\n"));
  {
#line 101
  printf("CLOSE-DOCUMENT\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_DOCUMENT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_DOCUMENT\n"));
  {
#line 100
  printf("OPEN-DOCUMENT\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CLOSE_KML(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CLOSE_KML\n"));
  {
#line 99
  printf("CLOSE-KML\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN_KML(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN_KML\n"));
  {
#line 98
  printf("OPEN-KML\n");;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_SINGLECOR(yycontext *yy, char *yytext, int yyleng)
{
#define num3 yy->__val[-1]
#define num2 yy->__val[-2]
#define num1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SINGLECOR\n"));
  {
#line 93
  __ = NodePtr(new CoordinateNode(num1,num2,num3));;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef num3
#undef num2
#undef num1
}
YY_ACTION(void) yy_1_COORDINATES_LIST(yycontext *yy, char *yytext, int yyleng)
{
#define cor yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_COORDINATES_LIST\n"));
  {
#line 89
  __ = NodePtr(new CoordinateListNode()); __->children.push_back(cor);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef cor
}
YY_ACTION(void) yy_1_FULL_POINT_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define corList yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FULL_POINT_TAG\n"));
  {
#line 85
  __ = NodePtr(new PointNode(corList));;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef corList
}
YY_ACTION(void) yy_1_FULL_DESCRIPTION_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define descr yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FULL_DESCRIPTION_TAG\n"));
  {
#line 81
   __ = NodePtr(new DescriptionNode(descr));;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef descr
}
YY_ACTION(void) yy_1_FULL_NAME_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define name yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FULL_NAME_TAG\n"));
  {
#line 77
   __ = NodePtr(new NameNode(name)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef name
}
YY_ACTION(void) yy_3_MINOR_TAGS(yycontext *yy, char *yytext, int yyleng)
{
#define point yy->__val[-1]
#define description yy->__val[-2]
#define name yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_MINOR_TAGS\n"));
  {
#line 73
  __ = point;;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef point
#undef description
#undef name
}
YY_ACTION(void) yy_2_MINOR_TAGS(yycontext *yy, char *yytext, int yyleng)
{
#define point yy->__val[-1]
#define description yy->__val[-2]
#define name yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_MINOR_TAGS\n"));
  {
#line 71
  __ = description;;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef point
#undef description
#undef name
}
YY_ACTION(void) yy_1_MINOR_TAGS(yycontext *yy, char *yytext, int yyleng)
{
#define point yy->__val[-1]
#define description yy->__val[-2]
#define name yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_MINOR_TAGS\n"));
  {
#line 69
  __ = name;;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef point
#undef description
#undef name
}
YY_ACTION(void) yy_1_DESCRIPTORS(yycontext *yy, char *yytext, int yyleng)
{
#define minortag yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DESCRIPTORS\n"));
  {
#line 63
  
                            __ = NodePtr(new DescriptorsNode()); __->children.push_back(minortag);
                            ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef minortag
}
YY_ACTION(void) yy_1_FULL_LINESTRING_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define corList yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FULL_LINESTRING_TAG\n"));
  {
#line 58
  
                                                                                                                                                            __ = NodePtr(new LineStringNode(corList));;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef corList
}
YY_ACTION(void) yy_1_FULL_PLACEMARKER_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define descriptors yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FULL_PLACEMARKER_TAG\n"));
  {
#line 52
   
                                                                                                        __ = NodePtr(new PlacemarkerNode(descriptors)); 
                                                                                                    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef descriptors
}
YY_ACTION(void) yy_2_MAJOR_TAGS(yycontext *yy, char *yytext, int yyleng)
{
#define linestring yy->__val[-1]
#define placemarker yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_MAJOR_TAGS\n"));
  {
#line 46
  
                                        __ = linestring;
                                    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef linestring
#undef placemarker
}
YY_ACTION(void) yy_1_MAJOR_TAGS(yycontext *yy, char *yytext, int yyleng)
{
#define linestring yy->__val[-1]
#define placemarker yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_MAJOR_TAGS\n"));
  {
#line 42
  
                                        __ = placemarker;
                                        ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef linestring
#undef placemarker
}
YY_ACTION(void) yy_2_DOCUMENT(yycontext *yy, char *yytext, int yyleng)
{
#define majortag yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_DOCUMENT\n"));
  {
#line 36
  
                                                                __ = NodePtr(new DocumentNode());
                                                            ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef majortag
}
YY_ACTION(void) yy_1_DOCUMENT(yycontext *yy, char *yytext, int yyleng)
{
#define majortag yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DOCUMENT\n"));
  {
#line 32
  
                                                                                                __ = NodePtr(new DocumentNode()); __->children.push_back(majortag);
                                                                                            ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef majortag
}
YY_ACTION(void) yy_1_KML_DOC(yycontext *yy, char *yytext, int yyleng)
{
#define doc yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_KML_DOC\n"));
  {
#line 26
  
                                                                            __ = NodePtr(new KMLNode(doc)); //expecting a document node as param
                                                                        ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef doc
}
YY_ACTION(void) yy_1_PROGRAM(yycontext *yy, char *yytext, int yyleng)
{
#define kml yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PROGRAM\n"));
  {
#line 17
  
                    program = kml; 
                    #if DEBUG == 1 
                        printf("Valid Doc!\n"); 
                    #endif
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef kml
}

YY_RULE(int) yy_COMMA_DELIMETER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMA_DELIMETER"));  if (!yymatchChar(yy, ',')) goto l1;  yyDo(yy, yy_1_COMMA_DELIMETER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA_DELIMETER", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA_DELIMETER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMBER_LITERAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMBER_LITERAL"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l2;
#undef yytext
#undef yyleng
  }
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\010\000\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l4;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }
  l4:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  l5:;	
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l7;  goto l8;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }
  l8:;	
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  l11:;	
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;  goto l11;
  l12:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  }  goto l10;
  l9:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;
  }
  l10:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l2;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_NUMBER_LITERAL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER_LITERAL", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER_LITERAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_COORDINATE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_COORDINATE"));  if (!yymatchString(yy, "</coordinates>")) goto l13;  yyDo(yy, yy_1_CLOSE_COORDINATE, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_COORDINATE", yy->__buf+yy->__pos));
  return 1;
  l13:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_COORDINATE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SINGLECOR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "SINGLECOR"));
  l15:;	
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_EOL(yy)) goto l16;  goto l15;
  l16:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;
  }
  l17:;	
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;  if (!yy_WS(yy)) goto l18;  goto l17;
  l18:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;
  }  if (!yy_NUMBER_LITERAL(yy)) goto l14;  yyDo(yy, yySet, -3, 0);  if (!yy_COMMA_DELIMETER(yy)) goto l14;  if (!yy_NUMBER_LITERAL(yy)) goto l14;  yyDo(yy, yySet, -2, 0);  if (!yy_COMMA_DELIMETER(yy)) goto l14;  if (!yy_NUMBER_LITERAL(yy)) goto l14;  yyDo(yy, yySet, -1, 0);
  l19:;	
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yy_EOL(yy)) goto l20;  goto l19;
  l20:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;
  }
  l21:;	
  {  int yypos22= yy->__pos, yythunkpos22= yy->__thunkpos;  if (!yy_WS(yy)) goto l22;  goto l21;
  l22:;	  yy->__pos= yypos22; yy->__thunkpos= yythunkpos22;
  }  yyDo(yy, yy_1_SINGLECOR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SINGLECOR", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SINGLECOR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_COORDINATE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_COORDINATE"));  if (!yymatchString(yy, "<coordinates>")) goto l23;  yyDo(yy, yy_1_OPEN_COORDINATE, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_COORDINATE", yy->__buf+yy->__pos));
  return 1;
  l23:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_COORDINATE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_POINT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_POINT"));  if (!yymatchString(yy, "</Point>")) goto l24;  yyDo(yy, yy_1_CLOSE_POINT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_POINT", yy->__buf+yy->__pos));
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_POINT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_POINT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_POINT"));  if (!yymatchString(yy, "<Point>")) goto l25;  yyDo(yy, yy_1_OPEN_POINT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_POINT", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_POINT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_DESCRIPTION(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_DESCRIPTION"));  if (!yymatchString(yy, "</description>")) goto l26;  yyDo(yy, yy_1_CLOSE_DESCRIPTION, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_DESCRIPTION", yy->__buf+yy->__pos));
  return 1;
  l26:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_DESCRIPTION", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_DESCRIPTION(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_DESCRIPTION"));  if (!yymatchString(yy, "<description>")) goto l27;  yyDo(yy, yy_1_OPEN_DESCRIPTION, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_DESCRIPTION", yy->__buf+yy->__pos));
  return 1;
  l27:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_DESCRIPTION", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_NAME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_NAME"));  if (!yymatchString(yy, "</name>")) goto l28;  yyDo(yy, yy_1_CLOSE_NAME, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_NAME", yy->__buf+yy->__pos));
  return 1;
  l28:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_NAME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRING_LITERAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRING_LITERAL"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l29;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\000\000\000\376\377\377\007\376\377\377\027\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l29;
  l30:;	
  {  int yypos31= yy->__pos, yythunkpos31= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\000\000\000\376\377\377\007\376\377\377\027\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l31;  goto l30;
  l31:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l29;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_STRING_LITERAL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_LITERAL", yy->__buf+yy->__pos));
  return 1;
  l29:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_LITERAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_NAME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_NAME"));  if (!yymatchString(yy, "<name>")) goto l32;  yyDo(yy, yy_1_OPEN_NAME, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_NAME", yy->__buf+yy->__pos));
  return 1;
  l32:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_NAME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FULL_POINT_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FULL_POINT_TAG"));
  l34:;	
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yy_EOL(yy)) goto l35;  goto l34;
  l35:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;
  }
  l36:;	
  {  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;  if (!yy_WS(yy)) goto l37;  goto l36;
  l37:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;
  }  if (!yy_OPEN_POINT(yy)) goto l33;
  l38:;	
  {  int yypos39= yy->__pos, yythunkpos39= yy->__thunkpos;  if (!yy_EOL(yy)) goto l39;  goto l38;
  l39:;	  yy->__pos= yypos39; yy->__thunkpos= yythunkpos39;
  }
  l40:;	
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yy_WS(yy)) goto l41;  goto l40;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }  if (!yy_COORDINATES_LIST(yy)) goto l33;  yyDo(yy, yySet, -1, 0);
  l42:;	
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;  if (!yy_EOL(yy)) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }
  l44:;	
  {  int yypos45= yy->__pos, yythunkpos45= yy->__thunkpos;  if (!yy_WS(yy)) goto l45;  goto l44;
  l45:;	  yy->__pos= yypos45; yy->__thunkpos= yythunkpos45;
  }  if (!yy_CLOSE_POINT(yy)) goto l33;
  l46:;	
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_EOL(yy)) goto l47;  goto l46;
  l47:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;
  }
  l48:;	
  {  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;  if (!yy_WS(yy)) goto l49;  goto l48;
  l49:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;
  }  yyDo(yy, yy_1_FULL_POINT_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FULL_POINT_TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l33:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FULL_POINT_TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FULL_DESCRIPTION_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FULL_DESCRIPTION_TAG"));
  l51:;	
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yy_EOL(yy)) goto l52;  goto l51;
  l52:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  }
  l53:;	
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yy_WS(yy)) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;
  }  if (!yy_OPEN_DESCRIPTION(yy)) goto l50;
  l55:;	
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yy_EOL(yy)) goto l56;  goto l55;
  l56:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;
  }
  l57:;	
  {  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;  if (!yy_WS(yy)) goto l58;  goto l57;
  l58:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;
  }  if (!yy_STRING_LITERAL(yy)) goto l50;  yyDo(yy, yySet, -1, 0);
  l59:;	
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yy_EOL(yy)) goto l60;  goto l59;
  l60:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;
  }
  l61:;	
  {  int yypos62= yy->__pos, yythunkpos62= yy->__thunkpos;  if (!yy_WS(yy)) goto l62;  goto l61;
  l62:;	  yy->__pos= yypos62; yy->__thunkpos= yythunkpos62;
  }  if (!yy_CLOSE_DESCRIPTION(yy)) goto l50;
  l63:;	
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yy_EOL(yy)) goto l64;  goto l63;
  l64:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;
  }
  l65:;	
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;  if (!yy_WS(yy)) goto l66;  goto l65;
  l66:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;
  }  yyDo(yy, yy_1_FULL_DESCRIPTION_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FULL_DESCRIPTION_TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FULL_DESCRIPTION_TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FULL_NAME_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FULL_NAME_TAG"));
  l68:;	
  {  int yypos69= yy->__pos, yythunkpos69= yy->__thunkpos;  if (!yy_EOL(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  }
  l70:;	
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yy_WS(yy)) goto l71;  goto l70;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }  if (!yy_OPEN_NAME(yy)) goto l67;
  l72:;	
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yy_EOL(yy)) goto l73;  goto l72;
  l73:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  }
  l74:;	
  {  int yypos75= yy->__pos, yythunkpos75= yy->__thunkpos;  if (!yy_WS(yy)) goto l75;  goto l74;
  l75:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;
  }  if (!yy_STRING_LITERAL(yy)) goto l67;  yyDo(yy, yySet, -1, 0);
  l76:;	
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yy_EOL(yy)) goto l77;  goto l76;
  l77:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;
  }
  l78:;	
  {  int yypos79= yy->__pos, yythunkpos79= yy->__thunkpos;  if (!yy_WS(yy)) goto l79;  goto l78;
  l79:;	  yy->__pos= yypos79; yy->__thunkpos= yythunkpos79;
  }  if (!yy_CLOSE_NAME(yy)) goto l67;
  l80:;	
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;  if (!yy_EOL(yy)) goto l81;  goto l80;
  l81:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;
  }
  l82:;	
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_WS(yy)) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }  yyDo(yy, yy_1_FULL_NAME_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FULL_NAME_TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FULL_NAME_TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MINOR_TAGS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "MINOR_TAGS"));
  {  int yypos85= yy->__pos, yythunkpos85= yy->__thunkpos;  if (!yy_FULL_NAME_TAG(yy)) goto l86;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_MINOR_TAGS, yy->__begin, yy->__end);  goto l85;
  l86:;	  yy->__pos= yypos85; yy->__thunkpos= yythunkpos85;  if (!yy_FULL_DESCRIPTION_TAG(yy)) goto l87;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_MINOR_TAGS, yy->__begin, yy->__end);  goto l85;
  l87:;	  yy->__pos= yypos85; yy->__thunkpos= yythunkpos85;  if (!yy_FULL_POINT_TAG(yy)) goto l84;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_MINOR_TAGS, yy->__begin, yy->__end);
  }
  l85:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "MINOR_TAGS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l84:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINOR_TAGS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_LINESTRING(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_LINESTRING"));  if (!yymatchString(yy, "</Linestring>")) goto l88;  yyDo(yy, yy_1_CLOSE_LINESTRING, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_LINESTRING", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_LINESTRING", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COORDINATES_LIST(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "COORDINATES_LIST"));
  l90:;	
  {  int yypos91= yy->__pos, yythunkpos91= yy->__thunkpos;  if (!yy_EOL(yy)) goto l91;  goto l90;
  l91:;	  yy->__pos= yypos91; yy->__thunkpos= yythunkpos91;
  }
  l92:;	
  {  int yypos93= yy->__pos, yythunkpos93= yy->__thunkpos;  if (!yy_WS(yy)) goto l93;  goto l92;
  l93:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;
  }  if (!yy_OPEN_COORDINATE(yy)) goto l89;
  l94:;	
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy_EOL(yy)) goto l95;  goto l94;
  l95:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  }
  l96:;	
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy_WS(yy)) goto l97;  goto l96;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }  if (!yy_SINGLECOR(yy)) goto l89;  yyDo(yy, yySet, -1, 0);
  l98:;	
  {  int yypos99= yy->__pos, yythunkpos99= yy->__thunkpos;  if (!yy_SINGLECOR(yy)) goto l99;  yyDo(yy, yySet, -1, 0);  goto l98;
  l99:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;
  }
  l100:;	
  {  int yypos101= yy->__pos, yythunkpos101= yy->__thunkpos;  if (!yy_EOL(yy)) goto l101;  goto l100;
  l101:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;
  }
  l102:;	
  {  int yypos103= yy->__pos, yythunkpos103= yy->__thunkpos;  if (!yy_WS(yy)) goto l103;  goto l102;
  l103:;	  yy->__pos= yypos103; yy->__thunkpos= yythunkpos103;
  }  if (!yy_CLOSE_COORDINATE(yy)) goto l89;
  l104:;	
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yy_EOL(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;
  }
  l106:;	
  {  int yypos107= yy->__pos, yythunkpos107= yy->__thunkpos;  if (!yy_WS(yy)) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos107; yy->__thunkpos= yythunkpos107;
  }  yyDo(yy, yy_1_COORDINATES_LIST, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "COORDINATES_LIST", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COORDINATES_LIST", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_LINESTRING(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_LINESTRING"));  if (!yymatchString(yy, "<Linestring>")) goto l108;  yyDo(yy, yy_1_OPEN_LINESTRING, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_LINESTRING", yy->__buf+yy->__pos));
  return 1;
  l108:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_LINESTRING", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_PLACEMARKER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_PLACEMARKER"));  if (!yymatchString(yy, "</Placemarker>")) goto l109;  yyDo(yy, yy_1_CLOSE_PLACEMARKER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_PLACEMARKER", yy->__buf+yy->__pos));
  return 1;
  l109:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_PLACEMARKER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DESCRIPTORS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "DESCRIPTORS"));  if (!yy_MINOR_TAGS(yy)) goto l110;  yyDo(yy, yySet, -1, 0);
  l111:;	
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yy_MINOR_TAGS(yy)) goto l112;  yyDo(yy, yySet, -1, 0);  goto l111;
  l112:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;
  }  yyDo(yy, yy_1_DESCRIPTORS, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DESCRIPTORS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DESCRIPTORS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_PLACEMARKER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_PLACEMARKER"));  if (!yymatchString(yy, "<Placemarker>")) goto l113;  yyDo(yy, yy_1_OPEN_PLACEMARKER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_PLACEMARKER", yy->__buf+yy->__pos));
  return 1;
  l113:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_PLACEMARKER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FULL_LINESTRING_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FULL_LINESTRING_TAG"));
  l115:;	
  {  int yypos116= yy->__pos, yythunkpos116= yy->__thunkpos;  if (!yy_EOL(yy)) goto l116;  goto l115;
  l116:;	  yy->__pos= yypos116; yy->__thunkpos= yythunkpos116;
  }
  l117:;	
  {  int yypos118= yy->__pos, yythunkpos118= yy->__thunkpos;  if (!yy_WS(yy)) goto l118;  goto l117;
  l118:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;
  }  if (!yy_OPEN_LINESTRING(yy)) goto l114;
  l119:;	
  {  int yypos120= yy->__pos, yythunkpos120= yy->__thunkpos;  if (!yy_EOL(yy)) goto l120;  goto l119;
  l120:;	  yy->__pos= yypos120; yy->__thunkpos= yythunkpos120;
  }
  l121:;	
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yy_WS(yy)) goto l122;  goto l121;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }  if (!yy_COORDINATES_LIST(yy)) goto l114;  yyDo(yy, yySet, -1, 0);
  l123:;	
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yy_EOL(yy)) goto l124;  goto l123;
  l124:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;
  }
  l125:;	
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_WS(yy)) goto l126;  goto l125;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }  if (!yy_CLOSE_LINESTRING(yy)) goto l114;
  l127:;	
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yy_EOL(yy)) goto l128;  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }
  l129:;	
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yy_WS(yy)) goto l130;  goto l129;
  l130:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;
  }  yyDo(yy, yy_1_FULL_LINESTRING_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FULL_LINESTRING_TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l114:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FULL_LINESTRING_TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FULL_PLACEMARKER_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "FULL_PLACEMARKER_TAG"));
  l132:;	
  {  int yypos133= yy->__pos, yythunkpos133= yy->__thunkpos;  if (!yy_EOL(yy)) goto l133;  goto l132;
  l133:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;
  }
  l134:;	
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yy_WS(yy)) goto l135;  goto l134;
  l135:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;
  }  if (!yy_OPEN_PLACEMARKER(yy)) goto l131;
  l136:;	
  {  int yypos137= yy->__pos, yythunkpos137= yy->__thunkpos;  if (!yy_EOL(yy)) goto l137;  goto l136;
  l137:;	  yy->__pos= yypos137; yy->__thunkpos= yythunkpos137;
  }
  l138:;	
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yy_WS(yy)) goto l139;  goto l138;
  l139:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;
  }  if (!yy_DESCRIPTORS(yy)) goto l131;  yyDo(yy, yySet, -1, 0);
  l140:;	
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yy_DESCRIPTORS(yy)) goto l141;  yyDo(yy, yySet, -1, 0);  goto l140;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }
  l142:;	
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yy_EOL(yy)) goto l143;  goto l142;
  l143:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;
  }
  l144:;	
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yy_WS(yy)) goto l145;  goto l144;
  l145:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;
  }  if (!yy_CLOSE_PLACEMARKER(yy)) goto l131;
  l146:;	
  {  int yypos147= yy->__pos, yythunkpos147= yy->__thunkpos;  if (!yy_EOL(yy)) goto l147;  goto l146;
  l147:;	  yy->__pos= yypos147; yy->__thunkpos= yythunkpos147;
  }
  l148:;	
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yy_WS(yy)) goto l149;  goto l148;
  l149:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;
  }  yyDo(yy, yy_1_FULL_PLACEMARKER_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FULL_PLACEMARKER_TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FULL_PLACEMARKER_TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_DOCUMENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_DOCUMENT"));  if (!yymatchString(yy, "</Document>")) goto l150;  yyDo(yy, yy_1_CLOSE_DOCUMENT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_DOCUMENT", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_DOCUMENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MAJOR_TAGS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "MAJOR_TAGS"));
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;  if (!yy_FULL_PLACEMARKER_TAG(yy)) goto l153;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_MAJOR_TAGS, yy->__begin, yy->__end);  goto l152;
  l153:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yy_FULL_LINESTRING_TAG(yy)) goto l151;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_MAJOR_TAGS, yy->__begin, yy->__end);
  }
  l152:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "MAJOR_TAGS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l151:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MAJOR_TAGS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_DOCUMENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_DOCUMENT"));  if (!yymatchString(yy, "<Document>")) goto l154;  yyDo(yy, yy_1_OPEN_DOCUMENT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_DOCUMENT", yy->__buf+yy->__pos));
  return 1;
  l154:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_DOCUMENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_KML(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_KML"));  if (!yymatchString(yy, "</Kml>")) goto l155;  yyDo(yy, yy_1_CLOSE_KML, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_KML", yy->__buf+yy->__pos));
  return 1;
  l155:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_KML", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DOCUMENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "DOCUMENT"));
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;
  l159:;	
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_EOL(yy)) goto l160;  goto l159;
  l160:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;
  }
  l161:;	
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;  if (!yy_WS(yy)) goto l162;  goto l161;
  l162:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;
  }  if (!yy_OPEN_DOCUMENT(yy)) goto l158;
  l163:;	
  {  int yypos164= yy->__pos, yythunkpos164= yy->__thunkpos;  if (!yy_EOL(yy)) goto l164;  goto l163;
  l164:;	  yy->__pos= yypos164; yy->__thunkpos= yythunkpos164;
  }
  l165:;	
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yy_WS(yy)) goto l166;  goto l165;
  l166:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;
  }  if (!yy_MAJOR_TAGS(yy)) goto l158;  yyDo(yy, yySet, -1, 0);
  l167:;	
  {  int yypos168= yy->__pos, yythunkpos168= yy->__thunkpos;  if (!yy_MAJOR_TAGS(yy)) goto l168;  yyDo(yy, yySet, -1, 0);  goto l167;
  l168:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;
  }
  l169:;	
  {  int yypos170= yy->__pos, yythunkpos170= yy->__thunkpos;  if (!yy_EOL(yy)) goto l170;  goto l169;
  l170:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;
  }
  l171:;	
  {  int yypos172= yy->__pos, yythunkpos172= yy->__thunkpos;  if (!yy_WS(yy)) goto l172;  goto l171;
  l172:;	  yy->__pos= yypos172; yy->__thunkpos= yythunkpos172;
  }  if (!yy_CLOSE_DOCUMENT(yy)) goto l158;
  l173:;	
  {  int yypos174= yy->__pos, yythunkpos174= yy->__thunkpos;  if (!yy_EOL(yy)) goto l174;  goto l173;
  l174:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;
  }
  l175:;	
  {  int yypos176= yy->__pos, yythunkpos176= yy->__thunkpos;  if (!yy_WS(yy)) goto l176;  goto l175;
  l176:;	  yy->__pos= yypos176; yy->__thunkpos= yythunkpos176;
  }  yyDo(yy, yy_1_DOCUMENT, yy->__begin, yy->__end);  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;
  l177:;	
  {  int yypos178= yy->__pos, yythunkpos178= yy->__thunkpos;  if (!yy_EOL(yy)) goto l178;  goto l177;
  l178:;	  yy->__pos= yypos178; yy->__thunkpos= yythunkpos178;
  }
  l179:;	
  {  int yypos180= yy->__pos, yythunkpos180= yy->__thunkpos;  if (!yy_WS(yy)) goto l180;  goto l179;
  l180:;	  yy->__pos= yypos180; yy->__thunkpos= yythunkpos180;
  }  if (!yy_OPEN_DOCUMENT(yy)) goto l156;
  l181:;	
  {  int yypos182= yy->__pos, yythunkpos182= yy->__thunkpos;  if (!yy_EOL(yy)) goto l182;  goto l181;
  l182:;	  yy->__pos= yypos182; yy->__thunkpos= yythunkpos182;
  }
  l183:;	
  {  int yypos184= yy->__pos, yythunkpos184= yy->__thunkpos;  if (!yy_WS(yy)) goto l184;  goto l183;
  l184:;	  yy->__pos= yypos184; yy->__thunkpos= yythunkpos184;
  }  if (!yy_CLOSE_DOCUMENT(yy)) goto l156;
  l185:;	
  {  int yypos186= yy->__pos, yythunkpos186= yy->__thunkpos;  if (!yy_EOL(yy)) goto l186;  goto l185;
  l186:;	  yy->__pos= yypos186; yy->__thunkpos= yythunkpos186;
  }
  l187:;	
  {  int yypos188= yy->__pos, yythunkpos188= yy->__thunkpos;  if (!yy_WS(yy)) goto l188;  goto l187;
  l188:;	  yy->__pos= yypos188; yy->__thunkpos= yythunkpos188;
  }  yyDo(yy, yy_2_DOCUMENT, yy->__begin, yy->__end);
  }
  l157:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "DOCUMENT", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOCUMENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_KML(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_KML"));  if (!yymatchString(yy, "<Kml>")) goto l189;  yyDo(yy, yy_1_OPEN_KML, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_KML", yy->__buf+yy->__pos));
  return 1;
  l189:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_KML", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_WS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "WS"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l190;  yyDo(yy, yy_1_WS, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "WS", yy->__buf+yy->__pos));
  return 1;
  l190:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos192= yy->__pos, yythunkpos192= yy->__thunkpos;  if (!yymatchChar(yy, '\r')) goto l192;  goto l193;
  l192:;	  yy->__pos= yypos192; yy->__thunkpos= yythunkpos192;
  }
  l193:;	  if (!yymatchChar(yy, '\n')) goto l191;  yyDo(yy, yy_1_EOL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l191:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_KML_DOC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "KML_DOC"));
  l195:;	
  {  int yypos196= yy->__pos, yythunkpos196= yy->__thunkpos;  if (!yy_EOL(yy)) goto l196;  goto l195;
  l196:;	  yy->__pos= yypos196; yy->__thunkpos= yythunkpos196;
  }
  l197:;	
  {  int yypos198= yy->__pos, yythunkpos198= yy->__thunkpos;  if (!yy_WS(yy)) goto l198;  goto l197;
  l198:;	  yy->__pos= yypos198; yy->__thunkpos= yythunkpos198;
  }  if (!yy_OPEN_KML(yy)) goto l194;
  l199:;	
  {  int yypos200= yy->__pos, yythunkpos200= yy->__thunkpos;  if (!yy_EOL(yy)) goto l200;  goto l199;
  l200:;	  yy->__pos= yypos200; yy->__thunkpos= yythunkpos200;
  }
  l201:;	
  {  int yypos202= yy->__pos, yythunkpos202= yy->__thunkpos;  if (!yy_WS(yy)) goto l202;  goto l201;
  l202:;	  yy->__pos= yypos202; yy->__thunkpos= yythunkpos202;
  }  if (!yy_DOCUMENT(yy)) goto l194;  yyDo(yy, yySet, -1, 0);
  l203:;	
  {  int yypos204= yy->__pos, yythunkpos204= yy->__thunkpos;  if (!yy_EOL(yy)) goto l204;  goto l203;
  l204:;	  yy->__pos= yypos204; yy->__thunkpos= yythunkpos204;
  }
  l205:;	
  {  int yypos206= yy->__pos, yythunkpos206= yy->__thunkpos;  if (!yy_WS(yy)) goto l206;  goto l205;
  l206:;	  yy->__pos= yypos206; yy->__thunkpos= yythunkpos206;
  }  if (!yy_CLOSE_KML(yy)) goto l194;
  l207:;	
  {  int yypos208= yy->__pos, yythunkpos208= yy->__thunkpos;  if (!yy_EOL(yy)) goto l208;  goto l207;
  l208:;	  yy->__pos= yypos208; yy->__thunkpos= yythunkpos208;
  }
  l209:;	
  {  int yypos210= yy->__pos, yythunkpos210= yy->__thunkpos;  if (!yy_WS(yy)) goto l210;  goto l209;
  l210:;	  yy->__pos= yypos210; yy->__thunkpos= yythunkpos210;
  }  yyDo(yy, yy_1_KML_DOC, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "KML_DOC", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l194:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "KML_DOC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROGRAM(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "PROGRAM"));  if (!yy_KML_DOC(yy)) goto l211;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_PROGRAM, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PROGRAM", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l211:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROGRAM", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_PROGRAM);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 121 "kml.leg"


int main()
{
    while (yyparse()){
    }
    if (!! program) {
    //program->print(std::cout);
    GeneratorPtr gen = generator(program);
    gen->generate(std::cout);
  } else {
    std::cout << "syntax error." << std::endl;
  }
  return 0;
    return 0;
}
